events {}

http {
  upstream chat_backend {
    # Docker's internal DNS will automatically resolve this to all available containers
    server chat-app:3000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://chat_backend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
    }
  }
}